### PR TITLE
Drop DebugHandlerPass

### LINKED ISSUE #187: Deprecated DebugHandlerPass
screenshot from 2016-11-08 15-00-22

```sh
The Symfony\Bundle\MonologBundle\DependencyInjection\Compiler\DebugHandlerPass class is deprecated since version 2.12 and will be removed in 3.0. Use AddDebugLogProcessorPass in FrameworkBundle instead: 1x
    1x in DefaultControllerTest::setUpBeforeClass from Tests\AppBundle\Controller
```

Using monolog-bundle v3.0.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Bug fix for 3.0 because this deprecated code should have been removed.
Fixes #187

### CODE REVIEW

**Comment by andreybolonin** [comment]
@nicolas-grekas  why is not merged?
Need approve about other symfony members?

**Comment by tgalopin** [comment]
This is indeed an issue for anyone using the Standard edition right now, we should consider merging this asap.

**Comment by nithinga** [comment]
@stof @fabpot Please take a look into this issue....

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by zerkms** [comment]
So now the `DebugHandlerPass` is removed and the `AddDebugLogProcessorPass` is not released yet.

How is it supposed to work?

**Comment by lsmith77** [comment]
any plans to make a new MonologBundle release?

**Comment by stof** [comment]
@nicolas-grekas this change is not good, as you have not dropped support for Symfony < 3.2 when dropping it, while the new pass in Symfony is not available in older versions

**Pull request merged**
