### PR TITLE
Deprecate DebugHandlerPass in favor of AddDebugLogProcessorPass in FrameworkBundle

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Related to https://github.com/symfony/symfony/pull/20416

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by Tobion** [comment]
The `AddDebugLogProcessorPass` is only available in Symfony 3.2. Does it mean monolog-bundle 3.x is only compatible with Symfony >= 3.2?

**Comment by xabbuh** [comment]
This (to be more precise, the changes done in #188) is indeed now breaking applications not using FrameworkBundle >= 3.2 (see symfony/symfony#21014 and https://github.com/symfony/monolog-bundle/pull/188#issuecomment-262410331). How do we deal with this now?

**Comment by stof** [comment]
@nicolas-grekas can you explain how you planned to handle this ?

**Comment by stof** [comment]
And this class cannot be deprecated, as it triggers deprecation for all Symfony LTS users

**Pull request merged**
