### PR TITLE
separated wire of handlers to channels

### PR DESCRIPTION
**Pull request by nahpeps**
moved the wire process to a separate function to allow compiler passes
of other bundles to add custom log channels.

The additional function makes it more easy to add dynamic channels like this:

```php

namespace BaseBundle\DependencyInjection\CompilerPass;

use Symfony\Bundle\MonologBundle\DependencyInjection\Compiler\LoggerChannelPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;
use Symfony\Component\DependencyInjection\Reference;

class LoggerChannelCompilerPass extends LoggerChannelPass {

    /**
     * @param ContainerBuilder $container
     * @api
     */
    public function process(ContainerBuilder $container)
    {

        $serviceList = $container->getParameter('service_list');

        foreach ($serviceList as $serviceIdentifier) {
            $channel = 'my.channel_prefix.' .  $serviceIdentifier;
            $channelService = 'monolog.logger.my_channel_prefix.' . $serviceIdentifier;

            $this->createLogger($channel, $channelService, $container);
        }
        $this->wireHandlersToChannels($container);
    }
}

```

### CODE REVIEW

**Comment by stof** [comment]
what is the use case for that ? Why not just tagging the service with the ``monolog.logger`` tag ?

**Comment by stof** [comment]
I'm not sure we want to expose ``wireHandlersToChannels`` as a supported extension point for which we need to keep BC.

**Comment by nahpeps** [comment]
The use case for me is, that I do not want to have the logger injected by constructor but by a function call.
As far I know, it is not possible to define the channel by using using the "calls" setting in DI like this:

```yaml
s7_numbirds_importer.midoco2.import_controller:
        class: MyClass
        arguments: [...]
        calls:
           - [setLogger, ["@my_logger"]]
```

In my case, the services are started in another bundle and get the matching logger channel injected.

**Comment by Seldaek** [comment]
@nahpeps I believe you can define it like that by injecting `@monolog.logger.foo` and then creating the channel in the config as documented at http://symfony.com/doc/current/cookbook/logging/channels_handlers.html#creating-your-own-channel

**Comment by stof** [comment]
changing the channel when injecting the logger through a method call is supported since the 2.1.0 version of the bundle.
So this is a bad use case for this change.

**Pull request closed without merging**
