### PR TITLE
Add Logmatic.io config

### PR DESCRIPTION
**Pull request by mRoca**
Add [Logmatic.io](https://logmatic.io/) configuration.

Caution : for the moment, the [LogmaticHandler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/LogmaticHandler.php) is only present on Monolog master branch.

### CODE REVIEW

**Comment by lyrixx** [comment]
:+1:

**Comment by fabpot** [comment]
... which means that it won't be easy to merge this one anytime soon as Monolog 2 beaks BC (which is fine).

**Comment by stof** [comment]
this should indeed stay in stand-by until we figure out the way to support Monolog 2 (remembering we cannot drop support for Monolog 1 as we still need to support PHP 5.x until the end of the Symfony 3.4 LTS, and switching to 2.x only would make it hard for the ecosystem). The hard part is figuring out how to handle custom handlers shipped in the bridge actually (as this is where there is a BC break). This bundle deals with configuration, and adapting constructor arguments according to the version is quite easy to do.

**Comment by alborq** [comment]
Up. Logmatic Handler has been release on Monolog.

**Comment by stof** [comment]
@alborq that's not true. It exists only in the master branch, which is the dev version of Monolog 2.x

**Comment by lyrixx** [comment]
Hello @mRoca 

Could you 
* rebase
* add a note in the CHANGELOG 
* throw an exception if the logmatic handler is configured but the class does not exist (1.X vs 2.X) 

Thanks

**Comment by fabpot** [comment]
I think this one can be close as Logmatic does not exist anymore.

**Comment by lyrixx** [comment]
Thanks again @mRoca and sorry for this delay

**Pull request closed without merging**
