### PR TITLE
Split configuration

### PR DESCRIPTION
**Pull request by raziel057**
For better readability and to fix https://github.com/symfony/monolog-bundle/issues/412
As proposed here https://github.com/symfony/monolog-bundle/issues/412#issuecomment-1091780515

Workarround for PHP issue php/php-src#8315

### CODE REVIEW

**Comment by raziel057** [comment]
Failing tests for PHPUnit Test for PHP < 7.4 is related to

**Comment by raziel057** [comment]
Hi there, it seems that the ticket on PHP side (marked as Feature https://github.com/php/php-src/issues/8315) will not be resolved soon I propose to accept the following PR where the config is split in multiple sub parts to avoid to encounter the PHP issue.

**Comment by ahajzik-crido** [comment]
Could you process this PR? Even though we have production env on linux, we develop on windows. It is hard to work doing "cache:clear" almost every time we need to test changes. We can't live long time with this issue. If it si not going to be solved we will be forced to abandon monolog logger.

**Review by Seldaek — APPROVED** [review]

**Comment by Seldaek** [comment]
Thanks - kinda hard to review all this code shifting, but I'm hoping you did it diligently :)

**Pull request merged**
