### PR TITLE
use ChildDefinition if available

### LINKED ISSUE #201: Usages of deprecated DefinitionDecorator
The current master makes use of `DefinitionDecorator` which will lead to deprecation notices as of symfony 3.3 and fatal errors as of 4.0.
Should we replace any `DefinitionDecorator` occurrence by `ChildDefinition` and update the `symfony/dependency-injection` requirement to `~3.3`  on master right now? 
If so I can work on this.

### PR DESCRIPTION
**Pull request by xabbuh**
This fixes #201.

### CODE REVIEW

**Comment by chalasr** [comment]
👍

**Comment by chalasr** [comment]
any merger here?

**Comment by derrabus** [comment]
This fix has only been applied to the 2.x branch. Any chance, we can merge it up to master as well?

**Comment by fabpot** [comment]
I've just merged 2.x into master.

**Pull request merged**
