### PR TITLE
add InsightOps support

### LINKED ISSUE #311: InsighOps handler is missing (but is present in monolog)
Hello,

InsightOps handler is supported on Monolog since the *[10 Sep 2017](https://github.com/Seldaek/monolog/blob/1.24.0/src/Monolog/Handler/InsightOpsHandler.php)*

Yet, when I try to configure it on Symfony side with `MonologBundle v3.4.0):
`There is no handler class defined for handler "insightops"`

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: insightops
            excluded_http_codes: [404, 405]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        insightops:
            type: insightops
            token: xxxxxx-xxxxxx-xxxxx
            region: eu
            level: info
```

(also the `region` key seems not to be supported inside the Configuration of the array node)

### PR DESCRIPTION
**Pull request by tristanbes**
closes #311

### CODE REVIEW

**Comment by tristanbes** [comment]
Tested on my project: it works 👍

**Comment by lyrixx** [comment]
Could you add a note in the CHANGELOG? 
It will be part of 3.5.0
Thanks

**Comment by tristanbes** [comment]
yes i'll add this tomorrow.

**Comment by tristanbes** [comment]
is that ok for you @lyrixx ?

**Comment by lyrixx** [comment]
Thanks for your work on this new feature!

**Pull request merged**
